management:
  context-path: /
spring:
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        tags: foo=bar, baz
        healthCheckInterval: 15s
        healthCheckPath: /health
        instanceId: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}
  application:
    name: consul-server-provider
